<Mandelbrot>
{
	<mainLoop>
		<loopTrap>none</loopTrap>,
		<loopSetup>[defaultSetup]</loopSetup>,
		<loopBreakCondition>[defaultBreak]</loopBreakCondition>,
	</mainLoop>
	<cpuVariables>
		<power>2</power>,
	</cpuVariables>
}
</Mandelbrot>