<FogIteration>
{
<flags>
	<skyOff>
	<sunOff>
</flags>
<variables>
	<maxDist>0</maxDist>,
	<maxDistRelease>0</maxDistRelease>,
	<maxSteps>100</maxSteps>,
	<maxStepsRelease>100</maxStepsRelease>,
</variables>
}
</FogIteration>
